// src/components/SocialLinks.tsx
import { motion } from 'framer-motion';
import socialData from '@/assets/socialLinks.json';

export const SocialLinks = () => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.8, delay: 0.4 }}
      className="glass-card p-6 flex flex-wrap gap-4 items-center justify-center lg:justify-start"
    >
      {socialData.map((item) => (
        <a
          key={item.name}
          href={item.url}
          target="_blank"
          rel="noopener noreferrer"
          className="group relative flex items-center justify-center p-3 rounded-2xl bg-white/5 hover:bg-white/20 transition-all duration-300 border border-white/10 hover:border-white/30"
          title={item.tip}
        >
          <img
            src={item.icon}
            alt={item.name}
            className="w-8 h-8 opacity-80 group-hover:opacity-100 group-hover:scale-110 transition-all duration-300 drop-shadow-md"
          />
          <span className="absolute -top-10 scale-0 group-hover:scale-100 transition-transform duration-300 bg-black/80 text-white text-xs py-1 px-2 rounded-md whitespace-nowrap pointer-events-none backdrop-blur-md">
            {item.tip}
          </span>
        </a>
      ))}
    </motion.div>
  );
};

// src/components/SocialLinks.vue
<template>
  <!-- 社交链接 -->
  <div class="social">
    <div class="link">
      <a
        v-for="(item, index) in socialLinks"
        :key="item.name"
        :href="item.url"
        target="_blank"
        @mouseenter="socialTip = item.tip"
        @mouseleave="socialTip = '通过这里联系我吧'"
        class="social-link"
        :style="{ animationDelay: `${index * 0.1}s` }"
      >
        <div class="icon-container">
          <img class="icon" :src="item.icon" height="24" />
        </div>
      </a>
    </div>
    <Transition name="fade">
      <span class="tip">{{ socialTip }}</span>
    </Transition>
  </div>
</template>

<script setup>
import socialLinks from "@/assets/socialLinks.json";

// 社交链接提示
const socialTip = ref("通过这里联系我吧");
</script>

<style lang="scss" scoped>
.social {
  margin-top: 1.5rem;
  display: flex;
  align-items: center;
  justify-content: space-between;
  max-width: 460px;
  width: 100%;
  height: 56px;
  background-color: transparent;
  border-radius: var(--card-border-radius);
  backdrop-filter: blur(0);
  animation: fade 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) 0.3s both;
  transition:
    background-color var(--transition-normal),
    backdrop-filter var(--transition-normal),
    box-shadow var(--transition-normal);
  @media (max-width: 840px) {
    max-width: 100%;
    justify-content: center;
    .link {
      justify-content: space-evenly !important;
      width: 90%;
    }
    .tip {
      display: none !important;
    }
  }

  .link {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 16px;
    .social-link {
      display: flex;
      align-items: center;
      justify-content: center;
      animation: fade 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
      .icon-container {
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        width: 40px;
        height: 40px;
        border-radius: 50%;
        background-color: rgba(255, 255, 255, 0.1);
        transition: all var(--transition-normal);
        &:hover {
          background-color: rgba(255, 255, 255, 0.2);
          transform: scale(1.15) rotate(5deg);
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
        }
        &:active {
          transform: scale(0.95);
        }
        .icon {
          transition: all var(--transition-normal);
          &:hover {
            transform: scale(1.2);
          }
        }
      }
    }
  }
  .tip {
    display: none;
    margin-right: 20px;
    font-size: 0.9rem;
    color: var(--text-secondary);
    animation: fade 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94);
  }
  @media (min-width: 768px) {
    &:hover {
      background-color: rgba(0, 0, 0, 0.4);
      backdrop-filter: blur(10px);
      -webkit-backdrop-filter: blur(10px);
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
      .tip {
        display: block;
      }
    }
  }
}
</style>
